controller_list:
  - name: ""
    action_ns: follow_joint_trajetrctory
    type: FollowJointTrajectory
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint

  # - name: "gripper_actions"
  #   action_ns: gripper_command
  #   type: GripperCommand
  #   default: true   
  #   command_joint: gripper_finger1_joint
  #   joints:
  #     - gripper_finger1_joint
