controller_list:
  - name: fake_arm_controller
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
  - name: fake_gripper_controller
    joints:
      - gripper_finger1_joint